name: Update Satellite Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-satellite-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install Python dependencies
        run: |
          cd scripts
          uv sync

      - name: Generate satellite data
        run: |
          cd scripts
          uv run python generate_satellite_paths.py

      - name: Commit updated satellite data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/satellite_paths_metadata.json
          git add public/tiles/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update satellite data and tiles (daily update)"
            git push
          fi

